# If you come from bash you might have to change your $PATH.
export PATH=$HOME/.bin:$HOME/bin:/usr/local/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH

# Fixes LLVM broken symlinks for finding its own fucking python lib.
export PYTHONPATH="/usr/lib/llvm-9/lib/python3.7/site-packages"

#Tell vdpau to use the libvdpau-va-gl wrapper
export VDPAU_DRIVER=va_gl

# Path to your oh-my-zsh installation.
export ZSH="/home/jblort/.oh-my-zsh"

# Default base branch for review, used with git review aliases
export REVIEW_BASE=develop


# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="gitster-custom"

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git safe-paste)

# If using Tilix on Linux:
#if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
#    source /etc/profile.d/vte.sh
#fi

source $ZSH/oh-my-zsh.sh

alias v=vim
alias g=git
alias cmbp="cmake --build --parallel"

# Launch ffprobe with warning cruft hidden with hide_banner
alias ffprobe="ffprobe -hide_banner"

alias gitwork="git config user.email <work mail here>"
alias githome="git config user.email jb.lort@gmail.com"

# A simple alias to find all the C++ source files in a repo using standard extenstions
alias findcpp="find . -name \"*.h\" -o -name \"*.inl\" -o -name \"*.cpp\" -o -name \"*.hpp\""

# Clang format helper
alias cf="clang-format -style=file -i"

# Format an entire C++ folder recursively with clang-format
alias cf-repo="findcpp | xargs cf"


# Source FZF and Autojump
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[[ -s /home/jblort/.autojump/etc/profile.d/autojump.sh ]] && source /home/jblort/.autojump/etc/profile.d/autojump.sh
